<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite A" duration-ms="302" started-at="2017-11-02T06:28:33Z" finished-at="2017-11-02T06:28:34Z">
    <groups>
    </groups>
    <test name="Test A1" duration-ms="152" started-at="2017-11-02T06:28:33Z" finished-at="2017-11-02T06:28:33Z">
      <class name="testSuiteA.TestA1">
        <test-method status="SKIP" signature="testA1_1()[pri:0, instance:testSuiteA.TestA1@4590c9c3]" name="testA1_1" duration-ms="58" started-at="2017-11-02T11:58:33Z" finished-at="2017-11-02T11:58:33Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test
	at testSuiteA.TestA1.testA1_1(TestA1.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1_1 -->
        <test-method status="PASS" signature="testA1_2()[pri:0, instance:testSuiteA.TestA1@4590c9c3]" name="testA1_2" duration-ms="4" started-at="2017-11-02T11:58:33Z" finished-at="2017-11-02T11:58:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1_2 -->
        <test-method status="FAIL" signature="testA1_3()[pri:0, instance:testSuiteA.TestA1@4590c9c3]" name="testA1_3" duration-ms="8" started-at="2017-11-02T11:58:33Z" finished-at="2017-11-02T11:58:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failed test case ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failed test case 
	at org.testng.Assert.fail(Assert.java:93)
	at testSuiteA.TestA1.testA1_3(TestA1.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1_3 -->
      </class> <!-- testSuiteA.TestA1 -->
    </test> <!-- Test A1 -->
    <test name="Test A2" duration-ms="23" started-at="2017-11-02T06:28:34Z" finished-at="2017-11-02T06:28:34Z">
      <class name="testSuiteA.TestA2">
        <test-method status="PASS" signature="testA2_1()[pri:0, instance:testSuiteA.TestA2@3a82f6ef]" name="testA2_1" duration-ms="2" started-at="2017-11-02T11:58:34Z" finished-at="2017-11-02T11:58:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA2_1 -->
        <test-method status="FAIL" signature="testA2_2()[pri:0, instance:testSuiteA.TestA2@3a82f6ef]" name="testA2_2" duration-ms="2" started-at="2017-11-02T11:58:34Z" finished-at="2017-11-02T11:58:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failed test case ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failed test case 
	at org.testng.Assert.fail(Assert.java:93)
	at testSuiteA.TestA2.testA2_2(TestA2.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA2_2 -->
        <test-method status="PASS" signature="testA2_3()[pri:0, instance:testSuiteA.TestA2@3a82f6ef]" name="testA2_3" duration-ms="3" started-at="2017-11-02T11:58:34Z" finished-at="2017-11-02T11:58:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA2_3 -->
      </class> <!-- testSuiteA.TestA2 -->
    </test> <!-- Test A2 -->
  </suite> <!-- Suite A -->
</testng-results>
